#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$root"
mkdir -p generated/go/contracts internal/contracts
if [[ -n "${GO_JSONSCHEMA_BIN:-}" ]]; then
  generator=("$GO_JSONSCHEMA_BIN")
else
  generator=(bash scripts/go/with-internal-toolchain.sh run github.com/atombender/go-jsonschema@v0.23.1)
fi
"${generator[@]}" \
  --package contracts --struct-name-from-title --only-models \
  --output generated/go/contracts/generated.go schemas/v1/*.schema.json
python - <<'PY'
from pathlib import Path
import json
files=[]
for p in sorted(Path('schemas/v1').glob('*.schema.json')):
    data=p.read_text()
    name=p.name.removesuffix('.schema.json')
    files.append((name,data,json.loads(data)['$id']))
out=['// Code generated by scripts/contracts/generate-go.sh. DO NOT EDIT.','package contracts','','var schemaFiles = map[string]schemaResource{']
for name,data,url in files:
    out.append(f'\t{json.dumps(name)}: {{URL: {json.dumps(url)}, Data: []byte({json.dumps(data)})}},')
out += ['}','']
Path('internal/contracts/schemas.go').write_text('\n'.join(out))
PY
bash scripts/go/with-internal-toolchain.sh fmt generated/go/contracts/generated.go
bash scripts/go/with-internal-toolchain.sh fmt internal/contracts/schemas.go
